import { sub } from 'date-fns';

export interface Form {
  image: string;
}

export interface PokemonInfo {
  image: string;
  forms?: Record<string, Form>;
}

export type PokemonList = Record<string, PokemonInfo>;

export const pokemonList: PokemonList = {
  bulbasaur: { image: '1.png' },
  ivysaur: { image: '2.png' },
  venusaur: {
    image: '3.png',
    forms: {
      mega: { image: '3-mega.png' },
      gmax: { image: '3-gigantamax.png' },
    },
  },
  charmander: { image: '4.png' },
  charmeleon: { image: '5.png' },
  charizard: {
    image: '6.png',
    forms: {
      megaX: { image: '6-mega-x.png' },
      megaY: { image: '6-mega-y.png' },
      gmax: { image: '6-gigantamax.png' },
    },
  },
  squirtle: { image: '7.png' },
  wartortle: { image: '8.png' },
  blastoise: {
    image: '9.png',
    forms: {
      mega: { image: '9-mega.png' },
      gmax: { image: '9-gigantamax.png' },
    },
  },
  caterpie: { image: '10.png' },
  metapod: { image: '11.png' },
  butterfree: {
    image: '12.png',
    forms: {
      gmax: { image: '12-gigantamax.png' },
    },
  },
  weedle: { image: '13.png' },
  kakuna: { image: '14.png' },
  beedrill: {
    image: '15.png',
    forms: {
      mega: { image: '15-mega.png' },
    },
  },
  pidgey: { image: '16.png' },
  pidgeotto: { image: '17.png' },
  pidgeot: {
    image: '18.png',
    forms: {
      mega: { image: '18-mega.png' },
    },
  },
  rattata: {
    image: '19.png',
    forms: {
      alola: { image: '19-alola.png' },
    },
  },
  raticate: {
    image: '20.png',
    forms: {
      alola: { image: '20-alola.png' },
    },
  },
  spearow: { image: '21.png' },
  fearow: { image: '22.png' },
  ekans: { image: '23.png' },
  arbok: { image: '24.png' },
  pikachu: {
    image: '25.png',
    forms: {
      gmax: { image: '25-gigantamax.png' },
    },
  },
  raichu: {
    image: '26.png',
    forms: {
      alola: { image: '26-alola.png' },
    },
  },
  sandshrew: {
    image: '27.png',
    forms: {
      alola: { image: '27-alola.png' },
    },
  },
  sandslash: {
    image: '28.png',
    forms: {
      alola: { image: '28-alola.png' },
    },
  },
  'nidoran-f': { image: '29.png' },
  nidorina: { image: '30.png' },
  nidoqueen: { image: '31.png' },
  'nidoran-m': { image: '32.png' },
  nidorino: { image: '33.png' },
  nidoking: { image: '34.png' },
  clefairy: { image: '35.png' },
  clefable: { image: '36.png' },
  vulpix: {
    image: '37.png',
    forms: {
      alola: { image: '37-alola.png' },
    },
  },
  ninetales: {
    image: '38.png',
    forms: {
      alola: { image: '38-alola.png' },
    },
  },
  jigglypuff: { image: '39.png' },
  wigglytuff: { image: '40.png' },
  zubat: { image: '41.png' },
  golbat: { image: '42.png' },
  oddish: { image: '43.png' },
  gloom: { image: '44.png' },
  vileplume: { image: '45.png' },
  paras: { image: '46.png' },
  parasect: { image: '47.png' },
  venonat: { image: '48.png' },
  venomoth: { image: '49.png' },
  diglett: {
    image: '50.png',
    forms: {
      alola: { image: '50-alola.png' },
    },
  },
  dugtrio: {
    image: '51.png',
    forms: {
      alola: { image: '51-alola.png' },
    },
  },
  meowth: {
    image: '52.png',
    forms: {
      alola: { image: '52-alola.png' },
      galarian: { image: '52-galarian.png' },
      gmax: { image: '52-gigantamax.png' },
    },
  },
  persian: {
    image: '53.png',
    forms: {
      alola: { image: '53-alola.png' },
    },
  },
  psyduck: { image: '54.png' },
  golduck: { image: '55.png' },
  mankey: { image: '56.png' },
  primeape: { image: '57.png' },
  growlithe: {
    image: '58.png',
    forms: {
      hisuian: { image: '58-hisuian.png' },
    },
  },
  arcanine: {
    image: '59.png',
    forms: {
      hisuian: { image: '59-hisuian.png' },
    },
  },
  poliwag: { image: '60.png' },
  poliwhirl: { image: '61.png' },
  poliwrath: { image: '62.png' },
  abra: { image: '63.png' },
  kadabra: { image: '64.png' },
  alakazam: {
    image: '65.png',
    forms: {
      mega: { image: '65-mega.png' },
    },
  },
  machop: { image: '66.png' },
  machoke: { image: '67.png' },
  machamp: {
    image: '68.png',
    forms: {
      gmax: { image: '68-gigantamax.png' },
    },
  },
  bellsprout: { image: '69.png' },
  weepinbell: { image: '70.png' },
  victreebel: { image: '71.png' },
  tentacool: { image: '72.png' },
  tentacruel: { image: '73.png' },
  geodude: {
    image: '74.png',
    forms: {
      alola: { image: '74-alola.png' },
    },
  },
  graveler: {
    image: '75.png',
    forms: {
      alola: { image: '75-alola.png' },
    },
  },
  golem: {
    image: '76.png',
    forms: {
      alola: { image: '76-alola.png' },
    },
  },
  ponyta: {
    image: '77.png',
    forms: {
      galarian: { image: '77-galarian.png' },
    },
  },
  rapidash: {
    image: '78.png',
    forms: {
      galarian: { image: '78-galarian.png' },
    },
  },
  slowpoke: {
    image: '79.png',
    forms: {
      galarian: { image: '79-galarian.png' },
    },
  },
  slowbro: {
    image: '80.png',
    forms: {
      mega: { image: '80-mega.png' },
      galarian: { image: '80-galarian.png' },
    },
  },
  magnemite: { image: '81.png' },
  magneton: { image: '82.png' },
  farfetchd: {
    image: '83.png',
    forms: {
      galarian: { image: '83-galarian.png' },
    },
  },
  doduo: { image: '84.png' },
  dodrio: { image: '85.png' },
  seel: { image: '86.png' },
  dewgong: { image: '87.png' },
  grimer: {
    image: '88.png',
    forms: {
      alola: { image: '88-alola.png' },
    },
  },
  muk: {
    image: '89.png',
    forms: {
      alola: { image: '89-alola.png' },
    },
  },
  shellder: { image: '90.png' },
  cloyster: { image: '91.png' },
  gastly: { image: '92.png' },
  haunter: { image: '93.png' },
  gengar: {
    image: '94.png',
    forms: {
      mega: { image: '94-mega.png' },
      gmax: { image: '94-gigantamax.png' },
    },
  },
  onix: { image: '95.png' },
  drowzee: { image: '96.png' },
  hypno: { image: '97.png' },
  krabby: { image: '98.png' },
  kingler: {
    image: '99.png',
    forms: {
      gmax: { image: '99-gigantamax.png' },
    },
  },
  voltorb: {
    image: '100.png',
    forms: {
      hisuian: { image: '100-hisuian.png' },
    },
  },
  electrode: {
    image: '101.png',
    forms: {
      hisuian: { image: '101-hisuian.png' },
    },
  },
  exeggcute: { image: '102.png' },
  exeggutor: {
    image: '103.png',
    forms: {
      alola: { image: '103-alola.png' },
    },
  },
  cubone: { image: '104.png' },
  marowak: {
    image: '105.png',
    forms: {
      alola: { image: '105-alola.png' },
    },
  },
  hitmonlee: { image: '106.png' },
  hitmonchan: { image: '107.png' },
  lickitung: { image: '108.png' },
  koffing: { image: '109.png' },
  weezing: {
    image: '110.png',
    forms: {
      galarian: { image: '110-galarian.png' },
    },
  },
  rhyhorn: { image: '111.png' },
  rhydon: { image: '112.png' },
  chansey: { image: '113.png' },
  tangela: { image: '114.png' },
  kangaskhan: {
    image: '115.png',
    forms: {
      mega: { image: '115-mega.png' },
    },
  },
  horsea: { image: '116.png' },
  seadra: { image: '117.png' },
  goldeen: { image: '118.png' },
  seaking: { image: '119.png' },
  staryu: { image: '120.png' },
  starmie: { image: '121.png' },
  'mr-mime': {
    image: '122.png',
    forms: {
      galarian: { image: '122-galarian.png' },
    },
  },
  scyther: { image: '123.png' },
  jynx: { image: '124.png' },
  electabuzz: { image: '125.png' },
  magmar: { image: '126.png' },
  pinsir: {
    image: '127.png',
    forms: {
      mega: { image: '127-mega.png' },
    },
  },
  tauros: {
    image: '128.png',
    forms: {
      paldean: { image: '128-paldean.png' },
      'paldean-aqua': { image: '128-paldean-aqua.png' },
      'paldean-blaze': { image: '128-paldean-blaze.png' },
    },
  },
  magikarp: { image: '129.png' },
  gyarados: {
    image: '130.png',
    forms: {
      mega: { image: '130-mega.png' },
    },
  },
  lapras: {
    image: '131.png',
    forms: {
      gmax: { image: '131-gigantamax.png' },
    },
  },
  ditto: { image: '132.png' },
  eevee: {
    image: '133.png',
    forms: {
      gmax: { image: '133-gigantamax.png' },
    },
  },
  vaporeon: { image: '134.png' },
  jolteon: { image: '135.png' },
  flareon: { image: '136.png' },
  porygon: { image: '137.png' },
  omanyte: { image: '138.png' },
  omastar: { image: '139.png' },
  kabuto: { image: '140.png' },
  kabutops: { image: '141.png' },
  aerodactyl: {
    image: '142.png',
    forms: {
      mega: { image: '142-mega.png' },
    },
  },
  snorlax: {
    image: '143.png',
    forms: {
      gmax: { image: '143-gigantamax.png' },
    },
  },
  articuno: {
    image: '144.png',
    forms: {
      galarian: { image: '144-galarian.png' },
    },
  },
  zapdos: {
    image: '145.png',
    forms: {
      galarian: { image: '145-galarian.png' },
    },
  },
  moltres: {
    image: '146.png',
    forms: {
      galarian: { image: '146-galarian.png' },
    },
  },
  dratini: { image: '147.png' },
  dragonair: { image: '148.png' },
  dragonite: { image: '149.png' },
  mewtwo: {
    image: '150.png',
    forms: {
      megaX: { image: '150-mega-x.png' },
      megaY: { image: '150-mega-y.png' },
    },
  },
  mew: { image: '151.png' },
  chikorita: { image: '152.png' },
  bayleef: { image: '153.png' },
  meganium: { image: '154.png' },
  cyndaquil: { image: '155.png' },
  quilava: { image: '156.png' },
  typhlosion: {
    image: '157.png',
    forms: {
      hisuian: { image: '157-hisuian.png' },
    },
  },
  totodile: { image: '158.png' },
  croconaw: { image: '159.png' },
  feraligatr: { image: '160.png' },
  sentret: { image: '161.png' },
  furret: { image: '162.png' },
  hoothoot: { image: '163.png' },
  noctowl: { image: '164.png' },
  ledyba: { image: '165.png' },
  ledian: { image: '166.png' },
  spinarak: { image: '167.png' },
  ariados: { image: '168.png' },
  crobat: { image: '169.png' },
  chinchou: { image: '170.png' },
  lanturn: { image: '171.png' },
  pichu: { image: '172.png' },
  cleffa: { image: '173.png' },
  igglybuff: { image: '174.png' },
  togepi: { image: '175.png' },
  togetic: { image: '176.png' },
  natu: { image: '177.png' },
  xatu: { image: '178.png' },
  mareep: { image: '179.png' },
  flaaffy: { image: '180.png' },
  ampharos: {
    image: '181.png',
    forms: {
      mega: { image: '181-mega.png' },
    },
  },
  bellossom: { image: '182.png' },
  marill: { image: '183.png' },
  azumarill: { image: '184.png' },
  sudowoodo: { image: '185.png' },
  politoed: { image: '186.png' },
  hoppip: { image: '187.png' },
  skiploom: { image: '188.png' },
  jumpluff: { image: '189.png' },
  aipom: { image: '190.png' },
  sunkern: { image: '191.png' },
  sunflora: { image: '192.png' },
  yanma: { image: '193.png' },
  wooper: {
    image: '194.png',
    forms: {
      paldean: { image: '194-paldean.png' },
    },
  },
  quagsire: { image: '195.png' },
  espeon: { image: '196.png' },
  umbreon: { image: '197.png' },
  murkrow: { image: '198.png' },
  slowking: {
    image: '199.png',
    forms: {
      galarian: { image: '199-galarian.png' },
    },
  },
  misdreavus: { image: '200.png' },
  unown: {
    image: '201.png',
    forms: {
      a: { image: '201-a.png' },
      b: { image: '201-b.png' },
      c: { image: '201-c.png' },
      d: { image: '201-d.png' },
      e: { image: '201-e.png' },
      f: { image: '201-f.png' },
      g: { image: '201-g.png' },
      h: { image: '201-h.png' },
      i: { image: '201-i.png' },
      j: { image: '201-j.png' },
      k: { image: '201-k.png' },
      l: { image: '201-l.png' },
      m: { image: '201-m.png' },
      n: { image: '201-n.png' },
      o: { image: '201-o.png' },
      p: { image: '201-p.png' },
      q: { image: '201-q.png' },
      r: { image: '201-r.png' },
      s: { image: '201-s.png' },
      t: { image: '201-t.png' },
      u: { image: '201-u.png' },
      v: { image: '201-v.png' },
      w: { image: '201-w.png' },
      x: { image: '201-x.png' },
      y: { image: '201-y.png' },
      z: { image: '201-z.png' },
      exclamation: { image: '201-exclamation.png' },
      question: { image: '201-question.png' },
    },
  },
  wobbuffet: { image: '202.png' },
  girafarig: { image: '203.png' },
  pineco: { image: '204.png' },
  forretress: { image: '205.png' },
  dunsparce: { image: '206.png' },
  gligar: { image: '207.png' },
  steelix: {
    image: '208.png',
    forms: {
      mega: { image: '208-mega.png' },
    },
  },
  snubbull: { image: '209.png' },
  granbull: { image: '210.png' },
  qwilfish: {
    image: '211.png',
    forms: {
      hisuian: { image: '211-hisuian.png' },
    },
  },
  scizor: {
    image: '212.png',
    forms: {
      mega: { image: '212-mega.png' },
    },
  },
  shuckle: { image: '213.png' },
  heracross: {
    image: '214.png',
    forms: {
      mega: { image: '214-mega.png' },
    },
  },
  sneasel: {
    image: '215.png',
    forms: {
      hisuian: { image: '215-hisuian.png' },
    },
  },
  teddiursa: { image: '216.png' },
  ursaring: {
    image: '217.png',
    forms: {
      bloodmoon: { image: '217-bloodmoon.png' },
    },
  },
  slugma: { image: '218.png' },
  magcargo: { image: '219.png' },
  swinub: { image: '220.png' },
  piloswine: { image: '221.png' },
  corsola: {
    image: '222.png',
    forms: {
      galarian: { image: '222-galarian.png' },
    },
  },
  remoraid: { image: '223.png' },
  octillery: { image: '224.png' },
  delibird: { image: '225.png' },
  mantine: { image: '226.png' },
  skarmory: { image: '227.png' },
  houndour: { image: '228.png' },
  houndoom: {
    image: '229.png',
    forms: {
      mega: { image: '229-mega.png' },
    },
  },
  kingdra: { image: '230.png' },
  phanpy: { image: '231.png' },
  donphan: { image: '232.png' },
  porygon2: { image: '233.png' },
  stantler: { image: '234.png' },
  smeargle: { image: '235.png' },
  tyrogue: { image: '236.png' },
  hitmontop: { image: '237.png' },
  smoochum: { image: '238.png' },
  elekid: { image: '239.png' },
  magby: { image: '240.png' },
  miltank: { image: '241.png' },
  blissey: { image: '242.png' },
  raikou: { image: '243.png' },
  entei: { image: '244.png' },
  suicune: { image: '245.png' },
  larvitar: { image: '246.png' },
  pupitar: { image: '247.png' },
  tyranitar: {
    image: '248.png',
    forms: {
      mega: { image: '248-mega.png' },
    },
  },
  lugia: { image: '249.png' },
  'ho-oh': { image: '250.png' },
  celebi: { image: '251.png' },
  treecko: { image: '252.png' },
  grovyle: { image: '253.png' },
  sceptile: {
    image: '254.png',
    forms: {
      mega: { image: '254-mega.png' },
    },
  },
  torchic: { image: '255.png' },
  combusken: { image: '256.png' },
  blaziken: {
    image: '257.png',
    forms: {
      mega: { image: '257-mega.png' },
    },
  },
  mudkip: { image: '258.png' },
  marshtomp: { image: '259.png' },
  swampert: {
    image: '260.png',
    forms: {
      mega: { image: '260-mega.png' },
    },
  },
  poochyena: { image: '261.png' },
  mightyena: { image: '262.png' },
  zigzagoon: {
    image: '263.png',
    forms: {
      galarian: { image: '263-galarian.png' },
    },
  },
  linoone: {
    image: '264.png',
    forms: {
      galarian: { image: '264-galarian.png' },
    },
  },
  wurmple: { image: '265.png' },
  silcoon: { image: '266.png' },
  beautifly: { image: '267.png' },
  cascoon: { image: '268.png' },
  dustox: { image: '269.png' },
  lotad: { image: '270.png' },
  lombre: { image: '271.png' },
  ludicolo: { image: '272.png' },
  seedot: { image: '273.png' },
  nuzleaf: { image: '274.png' },
  shiftry: { image: '275.png' },
  taillow: { image: '276.png' },
  swellow: { image: '277.png' },
  wingull: { image: '278.png' },
  pelipper: { image: '279.png' },
  ralts: { image: '280.png' },
  kirlia: { image: '281.png' },
  gardevoir: {
    image: '282.png',
    forms: {
      mega: { image: '282-mega.png' },
    },
  },
  surskit: { image: '283.png' },
  masquerain: { image: '284.png' },
  shroomish: { image: '285.png' },
  breloom: { image: '286.png' },
  slakoth: { image: '287.png' },
  vigoroth: { image: '288.png' },
  slaking: { image: '289.png' },
  nincada: { image: '290.png' },
  ninjask: { image: '291.png' },
  shedinja: { image: '292.png' },
  whismur: { image: '293.png' },
  loudred: { image: '294.png' },
  exploud: { image: '295.png' },
  makuhita: { image: '296.png' },
  hariyama: { image: '297.png' },
  azurill: { image: '298.png' },
  nosepass: { image: '299.png' },
  skitty: { image: '300.png' },
  delcatty: { image: '301.png' },
  sableye: {
    image: '302.png',
    forms: {
      mega: { image: '302-mega.png' },
    },
  },
  mawile: {
    image: '303.png',
    forms: {
      mega: { image: '303-mega.png' },
    },
  },
  aron: { image: '304.png' },
  lairon: { image: '305.png' },
  aggron: {
    image: '306.png',
    forms: {
      mega: { image: '306-mega.png' },
    },
  },
  meditite: { image: '307.png' },
  medicham: {
    image: '308.png',
    forms: {
      mega: { image: '308-mega.png' },
    },
  },
  electrike: { image: '309.png' },
  manectric: {
    image: '310.png',
    forms: {
      mega: { image: '310-mega.png' },
    },
  },
  plusle: { image: '311.png' },
  minun: { image: '312.png' },
  volbeat: { image: '313.png' },
  illumise: { image: '314.png' },
  roselia: { image: '315.png' },
  gulpin: { image: '316.png' },
  swalot: { image: '317.png' },
  carvanha: { image: '318.png' },
  sharpedo: {
    image: '319.png',
    forms: {
      mega: { image: '319-mega.png' },
    },
  },
  wailmer: { image: '320.png' },
  wailord: { image: '321.png' },
  numel: { image: '322.png' },
  camerupt: {
    image: '323.png',
    forms: {
      mega: { image: '323-mega.png' },
    },
  },
  torkoal: { image: '324.png' },
  spoink: { image: '325.png' },
  grumpig: { image: '326.png' },
  spinda: { image: '327.png' },
  trapinch: { image: '328.png' },
  vibrava: { image: '329.png' },
  flygon: { image: '330.png' },
  cacnea: { image: '331.png' },
  cacturne: { image: '332.png' },
  swablu: { image: '333.png' },
  altaria: {
    image: '334.png',
    forms: {
      mega: { image: '334-mega.png' },
    },
  },
  zangoose: { image: '335.png' },
  seviper: { image: '336.png' },
  lunatone: { image: '337.png' },
  solrock: { image: '338.png' },
  barboach: { image: '339.png' },
  whiscash: { image: '340.png' },
  corphish: { image: '341.png' },
  crawdaunt: { image: '342.png' },
  baltoy: { image: '343.png' },
  claydol: { image: '344.png' },
  lileep: { image: '345.png' },
  cradily: { image: '346.png' },
  anorith: { image: '347.png' },
  armaldo: { image: '348.png' },
  feebas: { image: '349.png' },
  milotic: { image: '350.png' },
  castform: {
    image: '351.png',
    forms: {
      sunny: { image: '351-sunny.png' },
      rainy: { image: '351-rainy.png' },
      snowy: { image: '351-snowy.png' },
    },
  },
  kecleon: { image: '352.png' },
  shuppet: { image: '353.png' },
  banette: {
    image: '354.png',
    forms: {
      mega: { image: '354-mega.png' },
    },
  },
  duskull: { image: '355.png' },
  dusclops: { image: '356.png' },
  tropius: { image: '357.png' },
  chimecho: { image: '358.png' },
  absol: {
    image: '359.png',
    forms: {
      mega: { image: '359-mega.png' },
    },
  },
  wynaut: { image: '360.png' },
  snorunt: { image: '361.png' },
  glalie: {
    image: '362.png',
    forms: {
      mega: { image: '362-mega.png' },
    },
  },
  spheal: { image: '363.png' },
  sealeo: { image: '364.png' },
  walrein: { image: '365.png' },
  clamperl: { image: '366.png' },
  huntail: { image: '367.png' },
  gorebyss: { image: '368.png' },
  relicanth: { image: '369.png' },
  luvdisc: { image: '370.png' },
  bagon: { image: '371.png' },
  shelgon: { image: '372.png' },
  salamence: {
    image: '373.png',
    forms: {
      mega: { image: '373-mega.png' },
    },
  },
  beldum: { image: '374.png' },
  metang: { image: '375.png' },
  metagross: {
    image: '376.png',
    forms: {
      mega: { image: '376-mega.png' },
    },
  },
  regirock: { image: '377.png' },
  regice: { image: '378.png' },
  registeel: { image: '379.png' },
  latias: {
    image: '380.png',
    forms: {
      mega: { image: '380-mega.png' },
    },
  },
  latios: {
    image: '381.png',
    forms: {
      mega: { image: '381-mega.png' },
    },
  },
  kyogre: {
    image: '382.png',
    forms: {
      primal: { image: '382-primal.png' },
    },
  },
  groudon: {
    image: '383.png',
    forms: {
      primal: { image: '383-primal.png' },
    },
  },
  rayquaza: {
    image: '384.png',
    forms: {
      mega: { image: '384-mega.png' },
    },
  },
  jirachi: { image: '385.png' },
  deoxys: {
    image: '386.png',
    forms: {
      attack: { image: '386-attack.png' },
      defense: { image: '386-defense.png' },
      speed: { image: '386-speed.png' },
    },
  },
  turtwig: { image: '387.png' },
  grotle: { image: '388.png' },
  torterra: { image: '389.png' },
  chimchar: { image: '390.png' },
  monferno: { image: '391.png' },
  infernape: { image: '392.png' },
  piplup: { image: '393.png' },
  prinplup: { image: '394.png' },
  empoleon: { image: '395.png' },
  starly: { image: '396.png' },
  staravia: { image: '397.png' },
  staraptor: { image: '398.png' },
  bidoof: { image: '399.png' },
  bibarel: { image: '400.png' },
  kricketot: { image: '401.png' },
  kricketune: { image: '402.png' },
  shinx: { image: '403.png' },
  luxio: { image: '404.png' },
  luxray: { image: '405.png' },
  budew: { image: '406.png' },
  roserade: { image: '407.png' },
  cranidos: { image: '408.png' },
  rampardos: { image: '409.png' },
  shieldon: { image: '410.png' },
  bastiodon: { image: '411.png' },
  burmy: {
    image: '412.png',
    forms: {
      sandy: { image: '412-sandy.png' },
      trash: { image: '412-trash.png' },
    },
  },
  wormadam: {
    image: '413.png',
    forms: {
      sandy: { image: '413-sandy.png' },
      trash: { image: '413-trash.png' },
    },
  },
  mothim: {
    image: '414.png',
  },
  combee: { image: '415.png' },
  vespiquen: { image: '416.png' },
  pachirisu: { image: '417.png' },
  buizel: { image: '418.png' },
  floatzel: { image: '419.png' },
  cherubi: { image: '420.png' },
  cherrim: {
    image: '421.png',
    forms: {
      sunshine: { image: '421-sunshine.png' },
    },
  },
  shellos: {
    image: '422.png',
    forms: {
      east: { image: '422-east.png' },
    },
  },
  gastrodon: {
    image: '423.png',
    forms: {
      east: { image: '423-east.png' },
    },
  },
  ambipom: { image: '424.png' },
  drifloon: { image: '425.png' },
  drifblim: { image: '426.png' },
  buneary: { image: '427.png' },
  lopunny: {
    image: '428.png',
    forms: {
      mega: { image: '428-mega.png' },
    },
  },
  mismagius: { image: '429.png' },
  honchkrow: { image: '430.png' },
  glameow: { image: '431.png' },
  purugly: { image: '432.png' },
  chingling: { image: '433.png' },
  stunky: { image: '434.png' },
  skuntank: { image: '435.png' },
  bronzor: { image: '436.png' },
  bronzong: { image: '437.png' },
  bonsly: { image: '438.png' },
  'mime-jr': { image: '439.png' },
  happiny: { image: '440.png' },
  chatot: { image: '441.png' },
  spiritomb: { image: '442.png' },
  gible: { image: '443.png' },
  gabite: { image: '444.png' },
  garchomp: {
    image: '445.png',
    forms: {
      mega: { image: '445-mega.png' },
    },
  },
  munchlax: { image: '446.png' },
  riolu: { image: '447.png' },
  lucario: {
    image: '448.png',
    forms: {
      mega: { image: '448-mega.png' },
    },
  },
  hippopotas: { image: '449.png' },
  hippowdon: { image: '450.png' },
  skorupi: { image: '451.png' },
  drapion: { image: '452.png' },
  croagunk: { image: '453.png' },
  toxicroak: { image: '454.png' },
  carnivine: { image: '455.png' },
  finneon: { image: '456.png' },
  lumineon: { image: '457.png' },
  mantyke: { image: '458.png' },
  snover: { image: '459.png' },
  abomasnow: {
    image: '460.png',
    forms: {
      mega: { image: '460-mega.png' },
    },
  },
  weavile: { image: '461.png' },
  magnezone: { image: '462.png' },
  lickilicky: { image: '463.png' },
  rhyperior: { image: '464.png' },
  tangrowth: { image: '465.png' },
  electivire: { image: '466.png' },
  magmortar: { image: '467.png' },
  togekiss: { image: '468.png' },
  yanmega: { image: '469.png' },
  leafeon: { image: '470.png' },
  glaceon: { image: '471.png' },
  gliscor: { image: '472.png' },
  mamoswine: { image: '473.png' },
  'porygon-z': { image: '474.png' },
  gallade: {
    image: '475.png',
    forms: {
      mega: { image: '475-mega.png' },
    },
  },
  probopass: { image: '476.png' },
  dusknoir: { image: '477.png' },
  froslass: { image: '478.png' },
  rotom: {
    image: '479.png',
    forms: {
      heat: { image: '479-heat.png' },
      wash: { image: '479-wash.png' },
      frost: { image: '479-frost.png' },
      fan: { image: '479-fan.png' },
      mow: { image: '479-mow.png' },
    },
  },
  uxie: { image: '480.png' },
  mesprit: { image: '481.png' },
  azelf: { image: '482.png' },
  dialga: {
    image: '483.png',
    forms: {
      origin: { image: '483-origin.png' },
    },
  },
  palkia: {
    image: '484.png',
    forms: {
      origin: { image: '484-origin.png' },
    },
  },
  heatran: { image: '485.png' },
  regigigas: { image: '486.png' },
  giratina: {
    image: '487.png',
    forms: {
      origin: { image: '487-origin.png' },
    },
  },
  cresselia: { image: '488.png' },
  phione: { image: '489.png' },
  manaphy: { image: '490.png' },
  darkrai: { image: '491.png' },
  shaymin: {
    image: '492.png',
    forms: {
      sky: { image: '492-sky.png' },
    },
  },
  arceus: {
    image: '493.png',
    forms: {
      bug: { image: '493-bug.png' },
      dark: { image: '493-dark.png' },
      dragon: { image: '493-dragon.png' },
      electric: { image: '493-electric.png' },
      fairy: { image: '493-fairy.png' },
      fighting: { image: '493-fighting.png' },
      fire: { image: '493-fire.png' },
      flying: { image: '493-flying.png' },
      ghost: { image: '493-ghost.png' },
      grass: { image: '493-grass.png' },
      ground: { image: '493-ground.png' },
      ice: { image: '493-ice.png' },
      normal: { image: '493-normal.png' },
      poison: { image: '493-poison.png' },
      psychic: { image: '493-psychic.png' },
      rock: { image: '493-rock.png' },
      steel: { image: '493-steel.png' },
      water: { image: '493-water.png' },
    },
  },
  victini: { image: '494.png' },
  snivy: { image: '495.png' },
  servine: { image: '496.png' },
  serperior: { image: '497.png' },
  tepig: { image: '498.png' },
  pignite: { image: '499.png' },
  emboar: { image: '500.png' },
  oshawott: { image: '501.png' },
  dewott: { image: '502.png' },
  samurott: {
    image: '503.png',
    forms: {
      hisuian: { image: '503-hisuian.png' },
    },
  },
  patrat: { image: '504.png' },
  watchog: { image: '505.png' },
  lillipup: { image: '506.png' },
  herdier: { image: '507.png' },
  stoutland: { image: '508.png' },
  purrloin: { image: '509.png' },
  liepard: { image: '510.png' },
  pansage: { image: '511.png' },
  simisage: { image: '512.png' },
  pansear: { image: '513.png' },
  simisear: { image: '514.png' },
  panpour: { image: '515.png' },
  simipour: { image: '516.png' },
  munna: { image: '517.png' },
  musharna: { image: '518.png' },
  pidove: { image: '519.png' },
  tranquill: { image: '520.png' },
  unfezant: { image: '521.png' },
  blitzle: { image: '522.png' },
  zebstrika: { image: '523.png' },
  roggenrola: { image: '524.png' },
  boldore: { image: '525.png' },
  gigalith: { image: '526.png' },
  woobat: { image: '527.png' },
  swoobat: { image: '528.png' },
  drilbur: { image: '529.png' },
  excadrill: { image: '530.png' },
  audino: {
    image: '531.png',
    forms: {
      mega: { image: '531-mega.png' },
    },
  },
  timburr: { image: '532.png' },
  gurdurr: { image: '533.png' },
  conkeldurr: { image: '534.png' },
  tympole: { image: '535.png' },
  palpitoad: { image: '536.png' },
  seismitoad: { image: '537.png' },
  throh: { image: '538.png' },
  sawk: { image: '539.png' },
  sewaddle: { image: '540.png' },
  swadloon: { image: '541.png' },
  leavanny: { image: '542.png' },
  venipede: { image: '543.png' },
  whirlipede: { image: '544.png' },
  scolipede: { image: '545.png' },
  cottonee: { image: '546.png' },
  whimsicott: { image: '547.png' },
  petilil: { image: '548.png' },
  lilligant: {
    image: '549.png',
    forms: {
      hisuian: { image: '549-hisuian.png' },
    },
  },
  basculin: {
    image: '550.png',
    forms: {
      'blue-striped': { image: '550-blue-striped.png' },
      'white-striped': { image: '550-white-striped.png' },
    },
  },
  sandile: { image: '551.png' },
  krokorok: { image: '552.png' },
  krookodile: { image: '553.png' },
  darumaka: {
    image: '554.png',
    forms: {
      galarian: { image: '554-galarian.png' },
    },
  },
  darmanitan: {
    image: '555.png',
    forms: {
      zen: { image: '555-zen.png' },
      galarian: { image: '555-galarian.png' },
      'galarian-zen': { image: '555-galarian-zen.png' },
    },
  },
  maractus: { image: '556.png' },
  dwebble: { image: '557.png' },
  crustle: { image: '558.png' },
  scraggy: { image: '559.png' },
  scrafty: { image: '560.png' },
  sigilyph: { image: '561.png' },
  yamask: {
    image: '562.png',
    forms: {
      galarian: { image: '562-galarian.png' },
    },
  },
  cofagrigus: { image: '563.png' },
  tirtouga: { image: '564.png' },
  carracosta: { image: '565.png' },
  archen: { image: '566.png' },
  archeops: { image: '567.png' },
  trubbish: { image: '568.png' },
  garbodor: {
    image: '569.png',
    forms: {
      gmax: {
        image: '569-gigantamax.png',
      },
    },
  },
  zorua: {
    image: '570.png',
    forms: {
      hisuian: { image: '570-hisuian.png' },
    },
  },
  zoroark: {
    image: '571.png',
    forms: {
      hisuian: { image: '571-hisuian.png' },
    },
  },
  minccino: { image: '572.png' },
  cinccino: { image: '573.png' },
  gothita: { image: '574.png' },
  gothorita: { image: '575.png' },
  gothitelle: { image: '576.png' },
  solosis: { image: '577.png' },
  duosion: { image: '578.png' },
  reuniclus: { image: '579.png' },
  ducklett: { image: '580.png' },
  swanna: { image: '581.png' },
  vanillite: { image: '582.png' },
  vanillish: { image: '583.png' },
  vanilluxe: { image: '584.png' },
  deerling: {
    image: '585.png',
    forms: {
      autumn: { image: '585-autumn.png' },
      winter: { image: '585-winter.png' },
      summer: { image: '585-summer.png' },
    },
  },
  sawsbuck: {
    image: '586.png',
    forms: {
      autumn: { image: '586-autumn.png' },
      winter: { image: '586-winter.png' },
      summer: { image: '586-summer.png' },
    },
  },
  emolga: { image: '587.png' },
  karrablast: { image: '588.png' },
  escavalier: { image: '589.png' },
  foongus: { image: '590.png' },
  amoonguss: { image: '591.png' },
  frillish: { image: '592.png' },
  jellicent: { image: '593.png' },
  alomomola: { image: '594.png' },
  joltik: { image: '595.png' },
  galvantula: { image: '596.png' },
  ferroseed: { image: '597.png' },
  ferrothorn: { image: '598.png' },
  klink: { image: '599.png' },
  klang: { image: '600.png' },
  klinklang: { image: '601.png' },
  tynamo: { image: '602.png' },
  eelektrik: { image: '603.png' },
  eelektross: { image: '604.png' },
  elgyem: { image: '605.png' },
  beheeyem: { image: '606.png' },
  litwick: { image: '607.png' },
  lampent: { image: '608.png' },
  chandelure: { image: '609.png' },
  axew: { image: '610.png' },
  fraxure: { image: '611.png' },
  haxorus: { image: '612.png' },
  cubchoo: { image: '613.png' },
  beartic: { image: '614.png' },
  cryogonal: { image: '615.png' },
  shelmet: { image: '616.png' },
  accelgor: { image: '617.png' },
  stunfisk: {
    image: '618.png',
    forms: {
      galarian: { image: '618-galarian.png' },
    },
  },
  mienfoo: { image: '619.png' },
  mienshao: { image: '620.png' },
  druddigon: { image: '621.png' },
  golett: { image: '622.png' },
  golurk: { image: '623.png' },
  pawniard: { image: '624.png' },
  bisharp: { image: '625.png' },
  bouffalant: { image: '626.png' },
  rufflet: { image: '627.png' },
  braviary: {
    image: '628.png',
    forms: {
      hisuian: { image: '628-hisuian.png' },
    },
  },
  vullaby: { image: '629.png' },
  mandibuzz: { image: '630.png' },
  heatmor: { image: '631.png' },
  durant: { image: '632.png' },
  deino: { image: '633.png' },
  zweilous: { image: '634.png' },
  hydreigon: { image: '635.png' },
  larvesta: { image: '636.png' },
  volcarona: { image: '637.png' },
  cobalion: { image: '638.png' },
  terrakion: { image: '639.png' },
  virizion: { image: '640.png' },
  tornadus: {
    image: '641.png',
    forms: {
      therian: { image: '641-therian.png' },
    },
  },
  thundurus: {
    image: '642.png',
    forms: {
      therian: { image: '642-therian.png' },
    },
  },
  reshiram: { image: '643.png' },
  zekrom: { image: '644.png' },
  landorus: {
    image: '645.png',
    forms: {
      therian: { image: '645-therian.png' },
    },
  },
  kyurem: {
    image: '646.png',
    forms: {
      black: { image: '646-black.png' },
      white: { image: '646-white.png' },
    },
  },
  keldeo: {
    image: '647.png',
    forms: {
      resolute: { image: '647-resolute.png' },
    },
  },
  meloetta: {
    image: '648.png',
    forms: {
      pirouette: { image: '648-pirouette.png' },
    },
  },
  genesect: {
    image: '649.png',
    forms: {
      douse: { image: '649-douse.png' },
      shock: { image: '649-shock.png' },
      burn: { image: '649-burn.png' },
      chill: { image: '649-chill.png' },
    },
  },
  chespin: { image: '650.png' },
  quilladin: { image: '651.png' },
  chesnaught: { image: '652.png' },
  fennekin: { image: '653.png' },
  braixen: { image: '654.png' },
  delphox: { image: '655.png' },
  froakie: { image: '656.png' },
  frogadier: { image: '657.png' },
  greninja: {
    image: '658.png',
    forms: {
      ash: { image: '658-ash.png' },
    },
  },
  bunnelby: { image: '659.png' },
  diggersby: { image: '660.png' },
  fletchling: { image: '661.png' },
  fletchinder: { image: '662.png' },
  talonflame: { image: '663.png' },
  scatterbug: {
    image: '664.png',
    forms: {
      'icy-snow': { image: '664-icy-snow.png' },
    },
  },
  spewpa: {
    image: '665.png',
    forms: {
      'icy-snow': { image: '665-icy-snow.png' },
    },
  },
  vivillon: {
    image: '666.png',
    forms: {
      archipelago: { image: '666-archipelago.png' },
      continental: { image: '666-continental.png' },
      elegant: { image: '666-elegant.png' },
      fancy: { image: '666-fancy.png' },
      garden: { image: '666-garden.png' },
      'high-plains': { image: '666-high-plains.png' },
      'icy-snow': { image: '666-icy-snow.png' },
      jungle: { image: '666-jungle.png' },
      marine: { image: '666-marine.png' },
      meadow: { image: '666-meadow.png' },
      modern: { image: '666-modern.png' },
      monsoon: { image: '666-monsoon.png' },
      ocean: { image: '666-ocean.png' },
      'poke-ball': { image: '666-poke-ball.png' },
      polar: { image: '666-polar.png' },
      river: { image: '666-river.png' },
      sandstorm: { image: '666-sandstorm.png' },
      savanna: { image: '666-savanna.png' },
      sun: { image: '666-sun.png' },
      tundra: { image: '666-tundra.png' },
    },
  },
  litleo: { image: '667.png' },
  pyroar: { image: '668.png' },
  flabebe: {
    image: '669.png',
    forms: {
      yellow: { image: '669-yellow.png' },
      orange: { image: '669-orange.png' },
      blue: { image: '669-blue.png' },
      white: { image: '669-white.png' },
    },
  },
  floette: {
    image: '670.png',
    forms: {
      yellow: { image: '670-yellow.png' },
      orange: { image: '670-orange.png' },
      blue: { image: '670-blue.png' },
      white: { image: '670-white.png' },
    },
  },
  florges: {
    image: '671.png',
    forms: {
      yellow: { image: '671-yellow.png' },
      orange: { image: '671-orange.png' },
      blue: { image: '671-blue.png' },
      white: { image: '671-white.png' },
    },
  },
  skiddo: { image: '672.png' },
  gogoat: { image: '673.png' },
  pancham: { image: '674.png' },
  pangoro: { image: '675.png' },
  furfrou: {
    image: '676.png',
    forms: {
      heart: { image: '676-heart.png' },
      diamond: { image: '676-diamond.png' },
      star: { image: '676-star.png' },
      pharaoh: { image: '676-pharaoh.png' },
      kabuki: { image: '676-kabuki.png' },
      'la-reine': { image: '676-la-reine.png' },
      matron: { image: '676-matron.png' },
      dandy: { image: '676-dandy.png' },
      debutante: { image: '676-debutante.png' },
    },
  },
  espurr: { image: '677.png' },
  meowstic: { image: '678.png' },
  honedge: { image: '679.png' },
  doublade: { image: '680.png' },
  aegislash: {
    image: '681.png',
    forms: {
      blade: { image: '681-blade.png' },
      shield: { image: '681-shield.png' },
    },
  },
  spritzee: { image: '682.png' },
  aromatisse: { image: '683.png' },
  swirlix: { image: '684.png' },
  slurpuff: { image: '685.png' },
  inkay: { image: '686.png' },
  malamar: { image: '687.png' },
  binacle: { image: '688.png' },
  barbaracle: { image: '689.png' },
  skrelp: { image: '690.png' },
  dragalge: { image: '691.png' },
  clauncher: { image: '692.png' },
  clawitzer: { image: '693.png' },
  helioptile: { image: '694.png' },
  heliolisk: { image: '695.png' },
  tyrunt: { image: '696.png' },
  tyrantrum: { image: '697.png' },
  amaura: { image: '698.png' },
  aurorus: { image: '699.png' },
  sylveon: { image: '700.png' },
  hawlucha: { image: '701.png' },
  dedenne: { image: '702.png' },
  carbink: { image: '703.png' },
  goomy: { image: '704.png' },
  sliggoo: {
    image: '705.png',
    forms: {
      hisuian: { image: '705-hisuian.png' },
    },
  },
  goodra: {
    image: '706.png',
    forms: {
      hisuian: { image: '706-hisuian.png' },
    },
  },
  klefki: { image: '707.png' },
  phantump: { image: '708.png' },
  trevenant: { image: '709.png' },
  pumpkaboo: { image: '710.png' },
  gourgeist: { image: '711.png' },
  bergmite: { image: '712.png' },
  avalugg: {
    image: '713.png',
    forms: {
      hisuian: { image: '713-hisuian.png' },
    },
  },
  noibat: { image: '714.png' },
  noivern: { image: '715.png' },
  xerneas: {
    image: '716.png',
    forms: {
      neutral: { image: '716-neutral.png' },
    },
  },
  yveltal: { image: '717.png' },
  zygarde: {
    image: '718.png',
    forms: {
      10: { image: '718-10.png' },
      50: { image: '718-50.png' },
      complete: { image: '718-complete.png' },
    },
  },
  diancie: {
    image: '719.png',
    forms: {
      mega: { image: '719-mega.png' },
    },
  },
  hoopa: {
    image: '720.png',
    forms: {
      unbound: { image: '720-unbound.png' },
    },
  },
  volcanion: { image: '721.png' },
  rowlet: { image: '722.png' },
  dartrix: { image: '723.png' },
  decidueye: {
    image: '724.png',
    forms: {
      hisuian: { image: '724-hisuian.png' },
    },
  },
  litten: { image: '725.png' },
  torracat: { image: '726.png' },
  incineroar: { image: '727.png' },
  popplio: { image: '728.png' },
  brionne: { image: '729.png' },
  primarina: { image: '730.png' },
  pikipek: { image: '731.png' },
  trumbeak: { image: '732.png' },
  toucannon: { image: '733.png' },
  yungoos: { image: '734.png' },
  gumshoos: { image: '735.png' },
  grubbin: { image: '736.png' },
  charjabug: { image: '737.png' },
  vikavolt: { image: '738.png' },
  crabrawler: { image: '739.png' },
  crabominable: { image: '740.png' },
  oricorio: {
    image: '741.png',
    forms: {
      'pom-pom': { image: '741-pom-pom.png' },
      pau: { image: '741-pau.png' },
      sensu: { image: '741-sensu.png' },
    },
  },
  cutiefly: { image: '742.png' },
  ribombee: { image: '743.png' },
  rockruff: { image: '744.png' },
  lycanroc: {
    image: '745.png',
    forms: {
      dusk: { image: '745-dusk.png' },
      midnight: { image: '745-midnight.png' },
    },
  },
  wishiwashi: {
    image: '746.png',
    forms: {
      school: { image: '746-school.png' },
    },
  },
  mareanie: { image: '747.png' },
  toxapex: { image: '748.png' },
  mudbray: { image: '749.png' },
  mudsdale: { image: '750.png' },
  dewpider: { image: '751.png' },
  araquanid: { image: '752.png' },
  fomantis: { image: '753.png' },
  lurantis: { image: '754.png' },
  morelull: { image: '755.png' },
  shiinotic: { image: '756.png' },
  salandit: { image: '757.png' },
  salazzle: { image: '758.png' },
  stufful: { image: '759.png' },
  bewear: { image: '760.png' },
  bounsweet: { image: '761.png' },
  steenee: { image: '762.png' },
  tsareena: { image: '763.png' },
  comfey: { image: '764.png' },
  oranguru: { image: '765.png' },
  passimian: { image: '766.png' },
  wimpod: { image: '767.png' },
  golisopod: { image: '768.png' },
  sandygast: { image: '769.png' },
  palossand: { image: '770.png' },
  pyukumuku: { image: '771.png' },
  'type-null': { image: '772.png' },
  silvally: {
    image: '773.png',
    forms: {
      bug: { image: '773-bug.png' },
      dark: { image: '773-dark.png' },
      dragon: { image: '773-dragon.png' },
      electric: { image: '773-electric.png' },
      fairy: { image: '773-fairy.png' },
      fighting: { image: '773-fighting.png' },
      fire: { image: '773-fire.png' },
      flying: { image: '773-flying.png' },
      ghost: { image: '773-ghost.png' },
      grass: { image: '773-grass.png' },
      ground: { image: '773-ground.png' },
      ice: { image: '773-ice.png' },
      normal: { image: '773-normal.png' },
      poison: { image: '773-poison.png' },
      psychic: { image: '773-psychic.png' },
      rock: { image: '773-rock.png' },
      steel: { image: '773-steel.png' },
      water: { image: '773-water.png' },
    },
  },
  minior: {
    image: '774.png',
    forms: {
      blue: { image: '774-blue.png' },
      green: { image: '774-green.png' },
      indigo: { image: '774-indigo.png' },
      orange: { image: '774-orange.png' },
      red: { image: '774-red.png' },
      violet: { image: '774-violet.png' },
      yellow: { image: '774-yellow.png' },
    },
  },
  komala: { image: '775.png' },
  turtonator: { image: '776.png' },
  togedemaru: { image: '777.png' },
  mimikyu: { image: '778.png' },
  bruxish: { image: '779.png' },
  drampa: { image: '780.png' },
  dhelmise: { image: '781.png' },
  'jangmo-o': { image: '782.png' },
  'hakamo-o': { image: '783.png' },
  'kommo-o': { image: '784.png' },
  'tapu-koko': { image: '785.png' },
  'tapu-lele': { image: '786.png' },
  'tapu-bulu': { image: '787.png' },
  'tapu-fini': { image: '788.png' },
  cosmog: { image: '789.png' },
  cosmoem: { image: '790.png' },
  solgaleo: { image: '791.png' },
  lunala: { image: '792.png' },
  nihilego: { image: '793.png' },
  buzzwole: { image: '794.png' },
  pheromosa: { image: '795.png' },
  xurkitree: { image: '796.png' },
  celesteela: { image: '797.png' },
  kartana: { image: '798.png' },
  guzzlord: { image: '799.png' },
  necrozma: {
    image: '800.png',
    forms: {
      dusk: { image: '800-dusk.png' },
      dawn: { image: '800-dawn.png' },
      ultra: { image: '800-ultra.png' },
    },
  },
  magearna: { image: '801.png' },
  marshadow: { image: '802.png' },
  poipole: { image: '803.png' },
  naganadel: { image: '804.png' },
  stakataka: { image: '805.png' },
  blacephalon: { image: '806.png' },
  zeraora: { image: '807.png' },
  meltan: { image: '808.png' },
  melmetal: {
    image: '809.png',
    forms: {
      gmax: { image: '809-gigantamax.png' },
    },
  },
  grookey: { image: '810.png' },
  thwackey: { image: '811.png' },
  rillaboom: {
    image: '812.png',
    forms: {
      gmax: { image: '812-gigantamax.png' },
    },
  },
  scorbunny: { image: '813.png' },
  raboot: { image: '814.png' },
  cinderace: {
    image: '815.png',
    forms: {
      gmax: { image: '815-gigantamax.png' },
    },
  },
  sobble: { image: '816.png' },
  drizzile: { image: '817.png' },
  inteleon: {
    image: '818.png',
    forms: {
      gmax: { image: '818-gigantamax.png' },
    },
  },
  skwovet: { image: '819.png' },
  greedent: { image: '820.png' },
  rookidee: { image: '821.png' },
  corvisquire: { image: '822.png' },
  corviknight: {
    image: '823.png',
    forms: {
      gmax: { image: '823-gigantamax.png' },
    },
  },
  blipbug: { image: '824.png' },
  dottler: { image: '825.png' },
  orbeetle: {
    image: '826.png',
    forms: {
      gmax: { image: '826-gigantamax.png' },
    },
  },
  nickit: { image: '827.png' },
  thievul: { image: '828.png' },
  gossifleur: { image: '829.png' },
  eldegoss: { image: '830.png' },
  wooloo: { image: '831.png' },
  dubwool: { image: '832.png' },
  chewtle: { image: '833.png' },
  drednaw: {
    image: '834.png',
    forms: {
      gmax: { image: '834-gigantamax.png' },
    },
  },
  yamper: { image: '835.png' },
  boltund: { image: '836.png' },
  rolycoly: { image: '837.png' },
  carkol: { image: '838.png' },
  coalossal: {
    image: '839.png',
    forms: {
      gmax: { image: '839-gigantamax.png' },
    },
  },
  applin: { image: '840.png' },
  flapple: {
    image: '841.png',
    forms: {
      gmax: { image: '841-gigantamax.png' },
    },
  },
  appletun: {
    image: '842.png',
    forms: {
      gmax: { image: '842-gigantamax.png' },
    },
  },
  silicobra: { image: '843.png' },
  sandaconda: {
    image: '844.png',
    forms: {
      gmax: { image: '844-gigantamax.png' },
    },
  },
  cramorant: { image: '845.png' },
  arrokuda: { image: '846.png' },
  barraskewda: { image: '847.png' },
  toxel: { image: '848.png' },
  toxtricity: {
    image: '849.png',
    forms: {
      lowkey: { image: '849-low-key.png' },
      gmax: { image: '849-gigantamax.png' },
    },
  },
  sizzlipede: { image: '850.png' },
  centiskorch: {
    image: '851.png',
    forms: {
      gmax: { image: '851-gigantamax.png' },
    },
  },
  clobbopus: { image: '852.png' },
  grapploct: { image: '853.png' },
  sinistea: { image: '854.png' },
  polteageist: { image: '855.png' },
  hatenna: { image: '856.png' },
  hattrem: { image: '857.png' },
  hatterene: {
    image: '858.png',
    forms: {
      gmax: { image: '858-gigantamax.png' },
    },
  },
  impidimp: { image: '859.png' },
  morgrem: { image: '860.png' },
  grimmsnarl: {
    image: '861.png',
    forms: {
      gmax: { image: '861-gigantamax.png' },
    },
  },
  obstagoon: { image: '862.png' },
  perrserker: { image: '863.png' },
  cursola: { image: '864.png' },
  sirfetchd: { image: '865.png' },
  'mr-rime': { image: '866.png' },
  runerigus: { image: '867.png' },
  milcery: { image: '868.png' },
  alcremie: {
    image: '869.png',
    forms: {
      gmax: { image: '869-gigantamax.png' },
    },
  },
  falinks: { image: '870.png' },
  pincurchin: { image: '871.png' },
  snom: { image: '872.png' },
  frosmoth: { image: '873.png' },
  stonjourner: { image: '874.png' },
  eiscue: {
    image: '875.png',
    forms: {
      noice: { image: '875-noice.png' },
    },
  },
  indeedee: {
    image: '876.png',
    forms: {
      female: { image: '876-female.png' },
    },
  },
  morpeko: { image: '877.png' },
  cufant: { image: '878.png' },
  copperajah: {
    image: '879.png',
    forms: {
      gmax: { image: '879-gigantamax.png' },
    },
  },
  dracozolt: { image: '880.png' },
  arctozolt: { image: '881.png' },
  dracovish: { image: '882.png' },
  arctovish: { image: '883.png' },
  duraludon: {
    image: '884.png',
    forms: {
      gmax: { image: '884-gigantamax.png' },
    },
  },
  dreepy: { image: '885.png' },
  drakloak: { image: '886.png' },
  dragapult: { image: '887.png' },
  zacian: {
    image: '888.png',
    forms: {
      crowned: { image: '888-crowned.png' },
    },
  },
  zamazenta: {
    image: '889.png',
    forms: {
      crowned: { image: '889-crowned.png' },
    },
  },
  eternatus: {
    image: '890.png',
    forms: {
      eternamax: { image: '890-gigantamax.png' },
    },
  },
  kubfu: { image: '891.png' },
  urshifu: {
    image: '892.png',
    forms: {
      single: { image: '892-single.png' },
      'single-gmax': { image: '892-single-gigantamax.png' },
      rapid: { image: '892-rapid.png' },
      'rapid-gmax': { image: '892-rapid-gigantamax.png' },
    },
  },
  zarude: { image: '893.png' },
  regieleki: { image: '894.png' },
  regidrago: { image: '895.png' },
  glastrier: { image: '896.png' },
  spectrier: { image: '897.png' },
  calyrex: {
    image: '898.png',
    forms: {
      ice: { image: '898-ice.png' },
      shadow: { image: '898-shadow.png' },
    },
  },
  wyrdeer: { image: '899.png' },
  kleavor: { image: '900.png' },
  ursaluna: { image: '901.png' },
  basculegion: {
    image: '902.png',
    forms: {
      female: { image: '902-female.png' },
    },
  },
  sneasler: { image: '903.png' },
  overqwil: { image: '904.png' },
  enamorus: {
    image: '905.png',
    forms: {
      therian: { image: '905-therian.png' },
    },
  },
  sprigatito: { image: '906.png' },
  floragato: { image: '907.png' },
  meowscarada: { image: '908.png' },
  fuecoco: { image: '909.png' },
  crocalor: { image: '910.png' },
  skeledirge: { image: '911.png' },
  quaxly: { image: '912.png' },
  quaxwell: { image: '913.png' },
  quaquaval: { image: '914.png' },
  lechonk: { image: '915.png' },
  oinkologne: { image: '916.png' },
  tarountula: { image: '917.png' },
  spidops: { image: '918.png' },
  nymble: { image: '919.png' },
  lokix: { image: '920.png' },
  pawmi: { image: '921.png' },
  pawmo: { image: '922.png' },
  pawmot: { image: '923.png' },
  tandemaus: { image: '924.png' },
  maushold: { image: '925.png' },
  fidough: { image: '926.png' },
  dachsbun: { image: '927.png' },
  smoliv: { image: '928.png' },
  dolliv: { image: '929.png' },
  arboliva: { image: '930.png' },
  squawkabilly: { image: '931.png' },
  nacli: { image: '932.png' },
  naclstack: { image: '933.png' },
  garganacl: { image: '934.png' },
  charcadet: { image: '935.png' },
  armarouge: { image: '936.png' },
  ceruledge: { image: '937.png' },
  tadbulb: { image: '938.png' },
  bellibolt: { image: '939.png' },
  wattrel: { image: '940.png' },
  kilowattrel: { image: '941.png' },
  maschiff: { image: '942.png' },
  mabosstiff: { image: '943.png' },
  shroodle: { image: '944.png' },
  grafaiai: { image: '945.png' },
  bramblin: { image: '946.png' },
  brambleghast: { image: '947.png' },
  toedscool: { image: '948.png' },
  toedscruel: { image: '949.png' },
  klawf: { image: '950.png' },
  capsakid: { image: '951.png' },
  scovillain: { image: '952.png' },
  rellor: { image: '953.png' },
  rabsca: { image: '954.png' },
  flittle: { image: '955.png' },
  espathra: { image: '956.png' },
  tinkatink: { image: '957.png' },
  tinkatuff: { image: '958.png' },
  tinkaton: { image: '959.png' },
  wiglett: { image: '960.png' },
  wugtrio: { image: '961.png' },
  bombirdier: { image: '962.png' },
  finizen: { image: '963.png' },
  palafin: {
    image: '964.png',
    forms: {
      hero: { image: '964-hero.png' },
    },
  },
  varoom: { image: '965.png' },
  revavroom: { image: '966.png' },
  cyclizar: { image: '967.png' },
  orthworm: { image: '968.png' },
  glimmet: { image: '969.png' },
  glimmora: { image: '970.png' },
  greavard: { image: '971.png' },
  houndstone: { image: '972.png' },
  flamigo: { image: '973.png' },
  cetoddle: { image: '974.png' },
  cetitan: { image: '975.png' },
  veluza: { image: '976.png' },
  dondozo: { image: '977.png' },
  tatsugiri: { image: '978.png' },
  annihilape: { image: '979.png' },
  clodsire: { image: '980.png' },
  farigiraf: { image: '981.png' },
  dudunsparce: { image: '982.png' },
  kingambit: { image: '983.png' },
  'great-tusk': { image: '984.png' },
  'scream-tail': { image: '985.png' },
  'brute-bonnet': { image: '986.png' },
  'flutter-mane': { image: '987.png' },
  'slither-wing': { image: '988.png' },
  'sandy-shocks': { image: '989.png' },
  'iron-treads': { image: '990.png' },
  'iron-bundle': { image: '991.png' },
  'iron-hands': { image: '992.png' },
  'iron-jugulis': { image: '993.png' },
  'iron-moth': { image: '994.png' },
  'iron-thorns': { image: '995.png' },
  frigibax: { image: '996.png' },
  arctibax: { image: '997.png' },
  baxcalibur: { image: '998.png' },
  gimmighoul: {
    image: '999.png',
    forms: {
      roaming: { image: '999-roaming.png' },
    },
  },
  gholdengo: { image: '1000.png' },
  'wo-chien': { image: '1001.png' },
  'chien-pao': { image: '1002.png' },
  'ting-lu': { image: '1003.png' },
  'chi-yu': { image: '1004.png' },
  'roaring-moon': { image: '1005.png' },
  'iron-valiant': { image: '1006.png' },
  koraidon: { image: '1007.png' },
  miraidon: { image: '1008.png' },
  'walking-wake': { image: '1009.png' },
  'iron-leaves': { image: '1010.png' },
  dipplin: { image: '1011.png' },
  poltchageist: { image: '1012.png' },
  sinistcha: { image: '1013.png' },
  okidogi: { image: '1014.png' },
  munkidori: { image: '1015.png' },
  fezandipiti: { image: '1016.png' },
  ogerpon: {
    image: '1017.png',
    forms: {
      'hearthflame-mask': { image: '1017-hearthflame-mask.png' },
      'wellspring-mask': { image: '1017-wellspring-mask.png' },
      'cornerstone-mask': { image: '1017-cornerstone-mask.png' },
    },
  },
  archaludon: { image: '1018.png' },
  hydrapple: { image: '1019.png' },
  'gouging-fire': { image: '1020.png' },
  'raging-bolt': { image: '1021.png' },
  'iron-boulder': { image: '1022.png' },
  'iron-crown': { image: '1023.png' },
  terapagos: {
    image: '1024.png',
    forms: {
      terastal: { image: '1024-terastal.png' },
      stellar: { image: '1024-stellar.png' },
    },
  },
  pecharunt: { image: '1025.png' },
  // miscellaneous sprites
  egg: { image: 'egg.png' },
  'manaphy-egg': {
    image: 'egg-manaphy.png',
  },
  substitute: { image: 'substitute.png' },
};
