export const regions = {
    eu: {
        name: 'Europe',
        countries: [
            'Austria',
            'Belgium',
            'Czech Republic',
            'Denmark',
            'Finland',
            'France',
            'Germany',
            'Greece',
            'Guernsey',
            'Isle of Man',
            'Ireland',
            'Italy',
            'Jersey',
            'Luxembourg',
            'Malta',
            'Netherlands',
            'Norway',
            'Poland',
            'Portugal',
            'Russia',
            'Spain',
            'Sweden',
            'Switzerland',
            'United Kingdom',
            'Slovakia',
            'Hungary',
            'Slovenia',
        ],
    },
    na: {
        name: 'North America',
        countries: ['United States', 'Canada'],
    },
    la: {
        name: 'Latin America',
        countries: [
            'Argentina',
            'Bolivia',
            'Brazil',
            'Chile',
            'Colombia',
            'Costa Rica',
            'Dominican Republic',
            'Ecuador',
            'El Salvador',
            'Guatemala',
            'Mexico',
            'Nicaragua',
            'Paraguay',
            'Peru',
            'Uruguay',
        ],
    },
    oc: {
        name: 'Oceania',
        countries: ['Australia', 'New Zealand'],
    },
    sa: {
        name: 'Middle East & South Africa',
        countries: [
            'South Africa',
            'Saudi Arabia',
            'United Arab Emirates',
            'Israel',
        ],
    },
    jp: {
        name: 'Japan',
        countries: ['Japan'],
    },
    sea: {
        name: 'South East Asia',
        countries: [
            'Brunei',
            'Cambodia',
            'Indonesia',
            'Laos',
            'Malaysia',
            'Myanmar',
            'Philippines',
            'Singapore',
            'Thailand',
            'Vietnam',
            'Hong Kong',
            'Taiwan',
        ],
    },
    sk: {
        name: 'South Korea',
        countries: ['South Korea'],
    },
    cn: {
        name: 'China',
        countries: ['China'],
    },
};
